server:
  port: 9090

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    proxy-target-class: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
