server:
  port: 0

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
